version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE_PRODUCTION}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: asdericel_web
    platform: linux/amd64
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "3000"
    volumes:
      - .:/app
      - ./config/master.key:/app/config/master.key:ro
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_ENV: production
    command: bundle exec puma -C config/puma.rb

  nginx:
    image: nginx:alpine
    container_name: asdericel_nginx
    platform: linux/amd64
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               sleep 12h & wait $${!};
               certbot renew;
             done"
