default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
 <<: *default
  database: postgres
  username: postgres
  password: db@5ervidor
  host: 72.60.255.26
  port: 5432

production:
  <<: *default
  database: <%= ENV['PGDATABASE_PRODUCTION'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
