default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['PGDATABASE_DEVELOPMENT'] %>
  username: <%= ENV['PGUSER_DEVELOPMENT'] %>
  password: <%= ENV['PGPASSWORD_DEVELOPMENT'] %>
  host: <%= ENV['PGHOST_DEVELOPMENT'] %>
  port: <%= ENV['PGPORT_DEVELOPMENT'] %>


production:
  <<: *default
  database: <%= ENV['PGDATABASE_PRODUCTION'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
